//Example
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const SET_AUTHORIZE = 'SET_AUTHORIZE';
export const REQUEST_AUTHORIZE = 'REQUEST_AUTHORIZE';